version: '3.8'
services:
  client:
    container_name: SecondBrain-client
    build:
      context: ./frontend
    ports:
      - '3333:3000'
    env_file: ./frontend/.env
    depends_on:
      - server
    volumes:
      - ./frontend:/app/
      - /app/node_modules
  server:
    container_name: SecondBrain-server
    build:
      context: ./backend
    ports:
      - '5000:5000'
    env_file: ./backend/.env
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
  mongodb:
    container_name: SecondBrain-mongodb
    image: mongo:latest
    volumes:
      - ~/mongodb:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb:
